---
title: "Homework2"
output: html_document
date: "2022-10-16"
---

```{r}
library(tidyverse)
library(tidymodels)
# Read in data
abs <- read_csv("C:/homework-2/homework-2/data/abalone.csv")
```

```{r}
# Question 1
abs$age <- abs$rings + 1.5
hist(abs$age)
# The distribution of "age" variable is skwed to the right with the median age of 10-15 years.
```


```{r}
# Question 2
set.seed(1012)

abs_split <- initial_split(abs, prop = 0.70,strata = age)
abs_train <- training(abs_split)
abs_test <- testing(abs_split)
```


```{r}
# Question 3
# We should exclude rings because we interpret age based on rings;otherwise, the model for rings and age will be perfectly mathched.
abs_recipe <- recipe(age ~ type+longest_shell+diameter+height+whole_weight+shucked_weight+viscera_weight+shell_weight, data = abs_train) %>% 
  step_dummy(all_nominal())
abs_recipe%>%
  step_interact(terms = ~ starts_with("type"):shucked_weight + longest_shell:diameter + shucked_weight:shell_weight) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors())

```


```{r}
# Question 4
lm_model <- linear_reg() %>% 
  set_engine("lm")
```


```{r}
# Question 5
lm_wflow <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(abs_recipe)

```


```{r}
# Question 6
lm_fit <- fit(lm_wflow, abs_train)
age_predict <- data.frame(longest_shell = 0.50, diameter = 0.10, height = 0.30, whole_weight = 4, shucked_weight = 1, viscera_weight = 2, shell_weight = 1, type = 'F')
predict(lm_fit, age_predict)
```
```{r}
library(yardstick)
abs_metrics <- metric_set(rmse, rsq, mae)

abs_train_res <- predict(lm_fit, new_data = abs_train %>% select(-age))
abs_train_res <- bind_cols(abs_train_res, abs_train %>% select(age))

rmse(abs_train_res, truth = age, estimate = .pred)
abs_metrics(abs_train_res, truth = age, 
                estimate = .pred)
#We can see that R-squared value is 0.544 and it means that 54.4% of the variability of outcome can be explained. This is not a significant level. Although there are a lot of factors to be considered as well, we can say that this model is not good at predicting the outcome.
```

